### ISSUE TITLE
Error saat run index.js

### ISSUE THREAD

**Issue by rynmaulana** [Sansekai/WaBot-Broadcast#1]
Error pas lagi run index.js

Error: Cannot find module '@adiwajshing/baileys'

**Comment by Sansekai** [comment]
@rynmaulana f3b79ee6a50ea088283cc1c8cf2e01939c7104fd udah ku fix ya, silakan di clone ulang repositorynya

**Comment by rynmaulana** [comment]
Untuk node_modules buat termuxnya gimana bang?

**Comment by Sansekai** [comment]
@rynmaulana udah ku update
